services:
  db:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'ny_taxi'
    ports:
      - '5433:5432'
    volumes:
      - vol-pgdata:/var/lib/postgresql/data
    networks:
      - 01-docker-terraform

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "8080:80"
    volumes:
      - vol-pgadmin_data:/var/lib/pgadmin
    networks:
      - 01-docker-terraform
  ingestion:
    container_name: ingestion
    build:
      context: .
      dockerfile: docker/ingestion.Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ny_taxi
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - ./data:/data
      - ./load_nyc_data.py:/app/load_nyc_data.py
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      - 01-docker-terraform

volumes:
  vol-pgdata:
    name: vol-pgdata
  vol-pgadmin_data:
    name: vol-pgadmin_data

networks:
  01-docker-terraform: